### ISSUE TITLE
FastProject cannot be moved after it is installed, due to a hard-coded "#!" in fastproject

### ISSUE THREAD

**Issue by alexgraehl** [YosefLab/FastProject#4]
Hi!

When fastproject is installed (on the Mac, at least), it hard-codes the install path in the top of the "fastproject" binary.

If you move or rename any part of the directory path afterward, fastproject will no longer run.

My suggestion would be changing the hard-coded python path to something like "#! /bin/env python" if possibile.

**Comment by deto** [comment]
Hi alexgraehl, 

Did you install it using the .sh script?  What those actually do is to create a completely separate, new Python install with all the FastProject dependencies.  I decided to give that as an option when I realized people had trouble installing into the system Python on a Mac (it's tricky to upgrade the numpy library).  So that install is supposed to use the Python that is installed with it, and not the user's default python.  

I agree it would be nice if the folder was portable, but I'm just using Continuum's Miniconda installer for this and they decided to hard-code the path :(

However, if you do want to install it so it just uses an existing Python install, you can do this with pip.  Look at the [instructions here](https://github.com/YosefLab/FastProject/wiki/Install-Instructions), under the second heading: "Installing FastProject with an existing Python install".

**Comment by alexgraehl** [comment]
Ah, interesting! Well, that explains it—I did indeed use that.

It's probably worth it to have the one-click download. Like, everything ran without me ending up in Dependency Hell, which was surprising and impressive!
